project/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from project import db
from project.models import User, Data
from project.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from project.users.picture_handler import add_profile_pic
import stripe
import pickle
import math
public_key='pk_test_51JqEebSEhjJ0OK35gH2wXCL17vaigmFloJ1dyEgpsYwLrwvqGT0PLlL3Fl7PASrPeXdfUkbZGTzyLc9h6qeacjyV00iyWEoBPG'
stripe.api_key = "sk_test_BQokikJOvBiI2HlWgH4olfQ2"
users=Blueprint('users',__name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f"Account created successfully! You are now logged in as {user.username}",category='success')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/data':
                next = url_for("users.data")

            return redirect(next)

    return render_template('login.html',form=form)



# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

@users.route('/payment_home')
def payment_home():
    return render_template('payment_home.html',public_key=public_key)


@users.route('/thankyou')
def thankyou():
    return render_template('thankyou.html')

@users.route('/payment',methods=['POST'])
def payment():
    customer = stripe.Customer.create(email=request.form['stripeEmail'],
                                      source=request.form['stripeToken'])

    # CHARGE/PAYMENT INFORMATION
    charge = stripe.Charge.create(
       customer=customer.id, 
       ammount=1999,
       currency='usd',
       description='Pay!!'
    )

    return redirect(url_for('thankyou'))


@users.route('/data',methods=['GET','POST'])
@login_required
def data():
    return render_template("data.html")


@users.route('/getmlmodeldata',methods=['GET','POST'])
@login_required
def getmlmodeldata():
    per_18 = request.form["No. of persons < 18"] 
    per_19 = request.form["No. of persons > 18"]
    water_appli = request.form["No. of Water Using Appliances"]
    garden = request.form["Garden"]
    season = request.form["Season"]
    weather = request.form["Weather"]
    water_avai = request.form["Water Available In Different Sources"]
    region = request.form["Region"]
    holiday = request.form["Holiday"]

    if garden == 'yes':
        garden = 1
    else:
        garden = 0

    season = 0

    if weather.lower() == 'cloudy':
        weather = 0
    elif weather.lower() == 'cold':
        weather = 1
    elif weather.lower() == 'dry':
        weather = 2
    elif weather.lower() == 'hot':
        weather = 3
    elif weather.lower() == 'humid':
        weather = 4
    else:
        weather = 5

    region = 0

    if holiday == 'no':
        holiday = 0
    else:
        holiday = 1

    input_list = [per_18,per_19,water_appli,garden,season,weather,water_avai,region,holiday]

    with open("/home/sachin269/Desktop/hacknitr/project/users/model_pickle.pkl", 'rb') as file:
        pickle_model = pickle.load(file)
        y_pred_from_pkl = pickle_model.predict([input_list])
    y_pred = 0.95*y_pred_from_pkl[0]
    y_pred = math.ceil(y_pred)
    return str(y_pred)

 

project/templates/account.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron" style="background-color: rgb(245,245,245,0.1);">
        <div align='center' >
            <h1> Welcome to the page for {{current_user.username}}</h1>
            <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
        </div>
    </div>
    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.username.label(class='form-group')}}
                {{form.username(class='form-control')}}
              </div>
            
              <div class="form-group">
              {{form.email.label(class='form-group')}}
              {{form.email(class='form-control')}}
              </div>
        
              <div class="form-group">
              {{form.picture.label(class='form-group')}}
              {{form.picture(class='form-control')}}
              </div>
        
              <div class="form-group">
               {{form.submit(class='btn btn-primary')}}
              </div>
        </form>
    </div>
{% endblock content %}

project/templates/contactus.html
{% extends 'base.html' %}

{% block content %}

<div class="container mb-5">
<div class="card" style="background-color: rgb(250,250,250,0.3); font-size: 1.5rem;">
    <div class="card-header text-center">
        <h2><b>Get In Touch</b></h4>
    </div>
    <div class="card-body">
        <form>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="inputEmail4" fontt-weight='bold'>First Name</label>
                  <input type="text" class="form-control" placeholder="First name">
                </div>
               
              </div>
              <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="inputEmail4">Last Name</label>
                    <input type="text" class="form-control" placeholder="Last name">
                </div>
                
              </div>
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
              </div>
              
            </div>
            
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="inputTb">Address</label>
                <textarea class="form-control" rows="5" id="tbComment"></textarea>
              </div>
            </div>
              
            <button type="submit" class="btn btn-success">Submit</button>
          </form>
        
    </div>
</div>
</div>
  {% endblock %}

project/templates/data.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script> -->
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    
  </head>
  <body style="background: url('https://images.pexels.com/photos/6775389/pexels-photo-6775389.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260');">
    <div class="container" style="margin-top: 15px;background-color:rgb(85, 74, 70,0.3);;">
      <div class="card" style="background-color: rgb(192, 192, 192);">
          <div class="card-header text-center" style="background-color: #4ccead;"><h4><b>Water Usage Prediction Analysis</b></h4></div>
          <div class="card-body">
      <div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="card-header text-center" style="background-color:rgb(128,219,170)"><h5><b>Family Data Input </b></h5></div>
                  <form id="inputForm">
                      
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> No. of persons < 18</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="No. of persons < 18" id="crimInputBoxId" value = "0">
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> No. of persons > 18</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="No. of persons > 18" id="" value = "0">
                          </div></div>
                          <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> No. of Water Using Appliances</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="No. of Water Using Appliances" id="" value = "0">
                          </div>
                      </div>
                      
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> Garden</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="Garden" id="" value = "0">
                          </div>
                      </div>
                      <br>
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> Season</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="Season" id="" value = "0">
                          </div>
                      </div>
                      <br>
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> Weather</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="Weather" id="" value = "0">
                          </div>
                      </div>
                      <br>
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> Water Available In Different Sources</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="Water Available In Different Sources" id="" value = "0">
                          </div>
                      </div>
                      <br>
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> Region</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="Region" id="" value = "0">
                          </div>
                      </div>
                      <br>
                      <div class="row">
                          <div class="col-md-3">
                              <label class="control-label"> Holiday</label>
                          </div>
                          <div class="col-md-9">
                              <input class="form-control" type="text" name="Holiday" id="" value = "0">
                          </div>
                      </div>
                      <br>
                      <div class="card-footer text-center">
                          <button type = "button" class="btn btn-info" onclick="getResult()" value = "submit" style="cursor: pointer;">Submit</button>
                      </div>
                  </div>
              </form>
              </div>
          </div>
          <br>
          <div class="col-md-12">
              <div class="card">
              <div class="card-header text-center" style="background-color: rgb(36, 184, 189);"><h5><b>Prediction Result</b></h5></div>
              <div class="card-body" style="background-color: rgb(182, 216, 208);">
                  <div class="row">
                      Model Predicted water Usage in litre->&nbsp;&nbsp; <span style="color:red"><p id="result"></p></span>
                  </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
    </div>
    <div class="modal" id="progressBar" role="dialog" data-backdrop="static">
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-info" role="status">
            <span class="sr-only">Loading...</span>
          </div>
    </div>
   
    </div>
    </div>
    <script>
      function getResult(){
          $("#progressBar").modal('show')
          $.ajax({
             type: "POST",
             url: "{{url_for('users.getmlmodeldata')}}",
             data: $("#inputForm").serialize(), // serializes the form's elements.
             success: function(data)
             {
                $("#result").html(data); // show response from the php script.
             },complete:function()
             {
              $("#progressBar").modal('hide')
             }
           });
      }
    </script>

  </body>
  </html>

project/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/fontawesome.min.css">
    <div class="position-absolute overflow-hidden  m-md-3 text-center" style="color: rgb(24, 22, 22);justify-content: center;padding-top: 150px; padding-bottom: 150px; min-height: 90%;">
        <img class="mb-4" src="url_for('static',filename='logo.png')" alt="">
        <div class=" p-lg mx-auto my-5">
            <h1 class="display-4 font-weight-normal">Water Resources Management
            </h1>
           <a class="btn btn-primary" href="{{url_for('users.register')}}" style="text-align: center; justify-content: center; color: black; font-size: 1.5rem;">Get Started</a>
        </div>
        <div class="product-device box-shadow d-none d-md-block"></div>
        <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
        <div class="centerdiv">
            <a href="https://m.facebook.com/sachin.mohanty.739" target="_blank"><i class="fab fa-facebook" style="color:rgb(1, 87, 136); font-size: 100px;margin: 10px; padding-top: 10px;"></i></a>
            <a href="https://twitter.com/NikhilCodes" target="_blank"<i class="fab fa-twitter"style="color:#00acee; font-size: 100px;margin: 10px; padding-top: 10px;"></i></a>
            <a href="https://www.instagram.com/sachinkumar_32/" target="_blank"><i class="fab fa-instagram-square"style="color:#5c4347; font-size: 100px;margin: 10px; padding-top: 9px;"></i></a>
            <a href="" target="_blank"><i class="fab fa-youtube"style="color:#e30707; font-size: 100px;margin: 10px; padding-top: 10px;"></i></a>
        </div>

    </div>
{% endblock content %}

project/templates/info.html
{% extends 'base.html' %}
{% block content %}
    <!-- <div class="jumbotron">
        <h1>Info about Our Project</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Recusandae numquam illum quis corporis deleniti explicabo harum molestias velit, libero, quam quaerat. Dignissimos dicta officiis quibusdam, sapiente nemo quos dolorem molestias?</p>
    </div> -->
    <div class="card text-center" style="background-color: rgba(245,245,245,0.4);">
        <div class="card-header" style="opacity: 1;">
          <p style="font-size: 3rem; font-weight: bold;"> Project H<sub>2</sub>O</p>
        </div>
        <div class="card-body">
          <h5 class="card-title"><span style="font-size: 1.8rem;">
            <b>About Our Project</b>
          </span></h5>
          <p class="card-text"><span style="font-size: 1.5rem; text-align: left;">
            Nowadays the worsening water crisis occurring in many regions has pushed them to the brink of war. Even it is predicted that the next world war might happen on water. Therefore it becomes need of the hour to take appropriate measures for the efficient management of the limited water resources available.
            <br>
            Here in our website, we have provided a login and register option where the user can sign up and login to provide the details. On the basis of the data provided, the ML model will allocate the required water to the user considering the various factors like wind speed, air pressure, humidity, topography, season, whether it is a festival day or not, availability of water in the source etc.
          </span></p>
          <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        <!-- <div class="card-footer text-muted">
          2 days ago
        </div> -->
      </div>
{% endblock content %}

project/templates/login.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="text-center">
        <form method="POST" class="form-signin" style="color: rgb(0, 0, 0);font-size: 1.5rem; ">
            {{form.hidden_tag()}}
            <h1 class="h1 mb-3 font-weight-normal" style="padding-top: 20px;">
                Please LogIn!!
            </h1>
            {{form.email.label()}}{{form.email(class="form-control")}}<br>
            {{form.password.label()}}{{form.password(class="form-control")}}<br>


            {{form.submit(class="btn btn-lg btn-block btn-success")}}
            <br>
            <div>
                <h6><span class="text-center" style="text-align: center;font-size: 1.5rem;">Do not have an account?</span></h6>
                <a class="btn btn-lg btn-secondary" href="{{ url_for('users.register') }}">Register</a>
             </div>

        </form>
    </div>
</body>
{% endblock content %}

project/templates/payment_home.html
{% extends 'base.html' %}
{% block content %}
    <div class="card text-center" style="background-color: rgba(245,245,245,0.4);">
        <div class="card-header" style="opacity: 1;">Welcome To the Payment Page</div>
        <div class="card-body">

      <!-- <h5 class="card-title">Special title treatment</h5> -->
      <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam amet blanditiis, inventore alias mollitia eius consequatur expedita voluptatem? Animi ratione delectus, porro eius tempora hic explicabo perferendis. Perspiciatis, numquam nisi.</p> -->
        <form action="{{url_for('users.payment')}}" method="POST">
            <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key={{public_key}}
            data-amount="1999"
            data-name="Water Bill"
            data-description="Pay"
            data-image="https://images.unsplash.com/photo-1514984879728-be0aff75a6e8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=35dcb9bb6f3e097541dd732a99c44766&auto=format&fit=crop&w=1576&q=80"
            data-locale="auto"
            data-zip-code="true">
            </script>
        </form>
      

        </div>
    
    </div>
{% endblock content %}

project/templates/register.html
{% extends 'base.html' %}
{% block content %}
<body class="text-center" >
    <div class="container">
        <form method="POST"  style="color: rgb(0, 0, 0);font-size: 1.5rem;">
            {{form.hidden_tag()}}
            <h1 class="h1 mb-3 font-weight-normal" style="padding-top: 20px;">
                Please Create Your Account
            </h1>
            {{form.email.label}}{{form.email(class="form-control")}}
            {{form.username.label}}{{form.username(class="form-control")}}<br>
            {{form.password.label}}{{form.password(class="form-control")}}<br>
            {{form.pass_confirm.label}}{{form.pass_confirm(class="form-control")}}<br>
            
            {{form.submit(class="btn btn-lg btn-block btn-success")}}
            <br>
            <div>
                <h6>
                    <span class="text-center" style="text-align: center;font-size: 1.5rem;">Already have an Account?</span>
                </h6>
                <a class="btn btn-lg btn-secondary text-center" href="{{ url_for('users.login') }}">Login</a>
             </div>
        </form>
    </div>
</body>
{% endblock content %}

project/templates/thankyou.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="jumbotron">
      <h1>Thank you for your donation!</h1>

    </div>

  </body>
  </html>